services:
  mongodb:
    image: mongo:7
    container_name: kairos-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: kairos

volumes:
  mongo_data:
